# https://pre-commit.com/
default_install_hook_types:
  - pre-commit
  - pre-push

repos:
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-eval
        entry: "nocheckin"
        language: pygrep
        files: ^(?!.pre-commit-config).*.(h|c|hpp|cpp|json|jsonc|yaml|yml|txt|py|md|toml|cfg|gd)$
        exclude: ^addons/.*$
        types: []
  - repo: https://github.com/google/yamlfmt
    rev: v0.19.0
    hooks:
      - id: yamlfmt
        language: system
  - repo: https://github.com/editorconfig-checker/editorconfig-checker
    rev: v3.6.1
    hooks:
      - id: editorconfig-checker
  # - repo: https://github.com/Scony/godot-gdscript-toolkit
  #   rev: 4.5.0
  #   hooks:
  #     - id: gdlint
  #       # name: gdlint
  #       # description: "gdlint - linter for GDScript"
  #       # entry: gdlint
  #       # language: python
  #       # language_version: python3
  #       # require_serial: true
  #       # types: [gdscript]
  - repo: local
    hooks:
      - id: gdscript-formatter
        name: gdscript-formatter
        entry: gdscript-formatter
        stages: [pre-commit, pre-merge-commit, pre-push, manual]
        require_serial: true
        always_run: true
        language: system
        types: [gdscript]
      - id: prettier
        name: prettier
        entry: prettier --parser json --write
        language: system
        require_serial: true
        files: \.(json|ldtk)$
        stages: [pre-commit, pre-merge-commit, pre-push, manual]
