import subprocess


def render_file(cog, filename, name, args):
    with open(f"src/{filename}") as in_file:
        lines = in_file.readlines()

    arg_names = []
    for line in lines:
        if line.startswith("// "):
            arg_names.append(line[3:].split(" ", 1)[0].strip())
        else:
            break

    s = filename.split(".t.", 1)

    out_file_name = f"{s[0]}.{name}.{s[1]}"
    out_file_path = f"codegen/cog/{out_file_name}"

    guard = "BF_COG_" + out_file_name.upper().replace(".", "_")

    with open(out_file_path, "w") as out_file:
        out_file.write(
            f"""// generated by bf_cog.py using 'src/{filename}', do not modify

            #ifdef {guard}
            #    error {guard} detected!
            #endif
            #define {guard}

            """
        )

        for i in range(len(arg_names), len(lines)):
            line = lines[i]
            for arg, arg_name in zip(args, arg_names, strict=True):
                line = line.replace(arg_name, arg)

            out_file.write(line)

    subprocess.run(f"clang-format -i {out_file_path}", check=True)

    cog.outl(f'\n#include "{out_file_name}"')
