# Imports.  {  ###
import json
import os
import re
import shutil
import string
import tempfile
from collections import defaultdict
from dataclasses import dataclass
from enum import Enum, unique
from functools import partial
from math import radians
from pathlib import Path
from typing import Any, TypeAlias

import bf_lib as bf
import pytest
import rpp
from bf_game import *  # noqa
from bf_typer import timing, timing_mark
from PIL import Image

# }

CODEGEN_DIR = Path("codegen")

CODEGEN_DISCLAIMER = """// automatically generated by bf_cli.py, do not modify
#pragma once

"""


def texture_ids_recursive_transform(
    gamelib_recursed, transform_texture_id, transform_texture_ids_list
) -> None:
    # {  ###
    if not isinstance(gamelib_recursed, dict):
        return

    for key, value in gamelib_recursed.items():
        if isinstance(value, dict):
            texture_ids_recursive_transform(
                value, transform_texture_id, transform_texture_ids_list
            )
        elif isinstance(key, str) and ("texture_ids" in key or "texture_id" in key):
            if "texture_ids" in key:
                assert isinstance(value, list)
                for v in value:
                    assert isinstance(v, str)
                transform_texture_ids_list(gamelib_recursed, key)
            elif "texture_id" in key:
                assert isinstance(value, str)
                transform_texture_id(gamelib_recursed, key)
        elif isinstance(value, list):
            for v in value:
                if isinstance(v, dict):
                    texture_ids_recursive_transform(
                        v, transform_texture_id, transform_texture_ids_list
                    )
    # }


def degrees_to_radians_recursive_transform(gamelib_recursed) -> None:
    # {  ###
    if not isinstance(gamelib_recursed, dict):
        return

    keys_to_replace = [key for key in gamelib_recursed if key.endswith("_deg")]

    for key in keys_to_replace:
        new_key = key.replace("_deg", "_rad")
        value = gamelib_recursed.pop(key)
        assert isinstance(value, (int, float))
        gamelib_recursed[new_key] = radians(value)

    del keys_to_replace

    for value in gamelib_recursed.values():
        if isinstance(value, dict):
            degrees_to_radians_recursive_transform(value)

        elif isinstance(value, list):
            for v in value:
                if isinstance(v, dict):
                    degrees_to_radians_recursive_transform(v)
    # }


@unique
class BrokenStringDatumType(Enum):
    INVALID = 0
    STRING = 1
    PLACEHOLDER = 2
    SPACE = 3


@dataclass
class BrokenStringDatum:
    type: BrokenStringDatumType
    string: str | None


StringGroup: TypeAlias = list[BrokenStringDatum]
StringLine: TypeAlias = list[StringGroup]


class StringMalformedError(Exception): ...


def process_group(string: str) -> StringGroup:
    # {  ###
    assert string
    assert " " not in string
    assert "\t" not in string
    assert "\n" not in string

    result: StringGroup = []

    while "{" in string:
        l = string.find("{")
        r = string.find("}")
        if l:
            result.append(
                BrokenStringDatum(type=BrokenStringDatumType.STRING, string=string[:l])
            )
        result.append(
            BrokenStringDatum(
                type=BrokenStringDatumType.PLACEHOLDER,
                string=string[l + 1 : r].split("__", 1)[0],
            )
        )
        string = string[r + 1 :]

    if string:
        result.append(BrokenStringDatum(type=BrokenStringDatumType.STRING, string=string))

    return result
    # }


def process_string(string: str) -> list[StringLine]:
    # {  ###
    string = bf.replace_double_spaces(string.strip().replace("\t", " ").replace("\r", ""))

    result: list[StringLine] = []

    sp = string.split("\n")
    if not any(sp):
        return result

    for line in sp:
        line_result: list[StringGroup] = []
        result.append(line_result)

        try:
            groups = line.split(" ")
            for i, group in enumerate(groups):
                if not line:
                    continue
                g = process_group(group)
                if i < len(groups) - 1:
                    g.append(
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None)
                    )
                line_result.append(g)

        except StringMalformedError:
            print(f"Line is malformed! `{line}`")
            raise

    return result
    # }


def test_process_group():
    # {  ###
    assert process_group("a") == [
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a")
    ]
    assert process_group("ab") == [
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ab")
    ]
    assert process_group("a,b") == [
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a,b")
    ]
    assert process_group("a{ABOBA}") == [
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a"),
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="ABOBA"),
    ]
    assert process_group("{ABOBA}a") == [
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="ABOBA"),
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a"),
    ]
    assert process_group("+{ABOBA},") == [
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="+"),
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="ABOBA"),
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string=","),
    ]
    assert process_group("{ABOBA},") == [
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="ABOBA"),
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string=","),
    ]
    assert process_group("{A}{B}") == [
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="A"),
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="B"),
    ]
    assert process_group("{A}b{C}") == [
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="A"),
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="b"),
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="C"),
    ]
    assert process_group("{AB}cd{EF}") == [
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="AB"),
        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="cd"),
        BrokenStringDatum(type=BrokenStringDatumType.PLACEHOLDER, string="EF"),
    ]
    # }


@pytest.mark.parametrize(  # {  ###
    ("string", "result"),
    [
        ("", []),
        ("\n\n", []),
        ("\t\t", []),
        (
            "ab",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ab"),
                    ],
                ],
            ],
        ),
        (
            "a. b",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a."),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="b"),
                    ],
                ],
            ],
        ),
        (
            "ab ke",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ab"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ke"),
                    ],
                ],
            ],
        ),
        (
            "ab\tke",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ab"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ke"),
                    ],
                ],
            ],
        ),
        (
            " ab  ke ",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ab"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="ke"),
                    ],
                ],
            ],
        ),
        (
            " +{CHANCE}% to explode ",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="+"),
                        BrokenStringDatum(
                            type=BrokenStringDatumType.PLACEHOLDER, string="CHANCE"
                        ),
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="%"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="to"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(
                            type=BrokenStringDatumType.STRING, string="explode"
                        ),
                    ],
                ],
            ],
        ),
        (
            " +{CHANCE__ALIAS}%, to explode ",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="+"),
                        BrokenStringDatum(
                            type=BrokenStringDatumType.PLACEHOLDER, string="CHANCE"
                        ),
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="%,"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="to"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(
                            type=BrokenStringDatumType.STRING, string="explode"
                        ),
                    ],
                ],
            ],
        ),
        (
            "{CHANCE}...",
            [
                [
                    [
                        BrokenStringDatum(
                            type=BrokenStringDatumType.PLACEHOLDER, string="CHANCE"
                        ),
                        BrokenStringDatum(
                            type=BrokenStringDatumType.STRING, string="..."
                        ),
                    ],
                ],
            ],
        ),
        (
            "b\na c",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="b"),
                    ],
                ],
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="c"),
                    ],
                ],
            ],
        ),
        (
            "b\n\na c",
            [
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="b"),
                    ],
                ],
                [],
                [
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="a"),
                        BrokenStringDatum(type=BrokenStringDatumType.SPACE, string=None),
                    ],
                    [
                        BrokenStringDatum(type=BrokenStringDatumType.STRING, string="c"),
                    ],
                ],
            ],
        ),
    ],
)  # }
def test_process_string(string: str, result: list[StringLine]) -> None:
    x = process_string(string)
    assert x == result


def _do_localization(genline, gamelib) -> tuple[set[int], dict[str, int]]:
    # {  ###
    _result = bf.read_localization_csv()
    loc_ids = _result.loc_ids
    loc_by_languages = _result.loc_by_languages

    locale_caps_offset = -1

    l = len(loc_ids)
    for i in range(l):
        loc = loc_ids[i]
        if loc.startswith("UI_"):
            if locale_caps_offset == -1:
                locale_caps_offset = len(loc_ids) - i
            loc_ids.append("{}__CAPS".format(loc))

    genline("constexpr int LOCALE_CAPS_OFFSET = {};\n".format(locale_caps_offset))
    bf.genenum(genline, "Loc", ["INVALID", *loc_ids], add_count=True)

    for strings in loc_by_languages.values():
        l = len(strings)
        for i in range(l):
            if loc_ids[i].startswith("UI_"):
                strings.append(strings[i].upper())
        strings.insert(0, "<<INVALID>>")

    loc_ids.insert(0, "<<INVALID>>")

    for strings in loc_by_languages.values():
        assert len(loc_ids) == len(strings)

    gamelib["localization_debug_strings"] = loc_ids

    locale_to_index: dict[str, int] = {key: i for i, key in enumerate(loc_ids)}
    index_to_locale = {i: codename for codename, i in locale_to_index.items()}

    SKIP_CHARACTERS = ("\n", "\t", "\r")
    codepoints: set[int] = set()

    for strings in loc_by_languages.values():
        for string_ in strings:
            codepoints.update(ord(c) for c in string_ if c not in SKIP_CHARACTERS)

    gamelib["localizations"] = [{"strings": x} for x in loc_by_languages.values()]

    # Making `broken_lines`.
    if 1:
        bf.genenum(
            genline, "BrokenStringDatumType", [x.name for x in BrokenStringDatumType]
        )
        all_russian_placeholders: list[tuple[int, str]] = []

        for loc_index, loc in enumerate(gamelib["localizations"]):
            is_russian = not loc_index
            broken_lines: list = []
            loc["broken_lines"] = broken_lines

            for string_index, string_ in enumerate(loc["strings"]):
                string_lines: list = []
                broken_lines.append({"lines": string_lines})
                string_placeholders_to_verify = set()

                for line in process_string(string_):
                    grs: list = []
                    string_lines.append({"groups": grs})

                    for group in line:
                        gr: list = []
                        grs.append({"strings": gr})

                        for datum in group:
                            placeholder: str | None = None

                            if datum.type == BrokenStringDatumType.PLACEHOLDER:
                                assert datum.string
                                placeholder_data = (string_index, datum.string)
                                placeholder = datum.string

                                if is_russian and (
                                    placeholder_data not in all_russian_placeholders
                                ):
                                    all_russian_placeholders.append(placeholder_data)

                                string_placeholders_to_verify.add(datum.string)

                            gr.append(
                                {
                                    "type": datum.type.value,
                                    "placeholder": placeholder,
                                    "string": datum.string,
                                }
                            )

                if not is_russian:
                    russian_placeholders = set(
                        x[1] for x in all_russian_placeholders if x[0] == string_index
                    )
                    assert string_placeholders_to_verify == russian_placeholders, (
                        "Translated string differs in placeholders",
                        bf.game_settings.languages[loc_index],
                        index_to_locale[string_index],
                    )

    return codepoints, locale_to_index
    # }


@timing
def do_audio(platform: bf.BuildPlatform) -> None:
    # {  ###
    AUDIO_SRC_DIR = bf.ASSETS_DIR / "sfx"
    AUDIO_DST_DIR = bf.RES_DIR
    AUDIO_POST_DST_DIR = bf.RES_DIR
    if platform.is_web():
        AUDIO_POST_DST_DIR = bf.PROJECT_DIR / "resp"
    bf.recursive_mkdir(AUDIO_DST_DIR)
    bf.recursive_mkdir(AUDIO_POST_DST_DIR)
    for folder in {AUDIO_DST_DIR, AUDIO_POST_DST_DIR}:
        for f in folder.glob("*.ogg"):
            f.unlink()

    src_files = {p for p in AUDIO_SRC_DIR.glob("*.ogg") if p.is_file()}

    # Removing sound files that wouldn't be exported by reaper.
    allowed_sounds = get_sounds_that_reaper_would_export()
    for src_file in src_files:
        if src_file.stem.startswith("music_"):
            continue
        if src_file.stem not in allowed_sounds:
            src_file.unlink()
    src_files = {
        x
        for x in src_files
        if (x.stem in allowed_sounds) or (x.stem.startswith("music_"))
    }

    # Making symlinks.
    for src_file in src_files:
        dst_folder = AUDIO_DST_DIR
        if src_file.name.startswith("music_"):
            dst_folder = AUDIO_POST_DST_DIR
        dst_file = dst_folder / (src_file.stem + ".ogg")
        dst_file.symlink_to(src_file)

    bf.log.info(f"Make symlinks for {len(src_files)} audio files")

    # Removing orphan audio files from `res` dir.
    orphans = []
    for folder in {AUDIO_DST_DIR, AUDIO_POST_DST_DIR}:
        for dst_file in folder.glob("*.ogg"):
            src_file = AUDIO_SRC_DIR / dst_file.relative_to(folder)
            if not src_file.exists():
                orphans.append(dst_file)
                dst_file.unlink()
    if orphans:
        bf.log.info(
            "Removed {} orphan audio files:\n{}".format(
                len(orphans), "\n".join(x for x in orphans)
            )
        )
    # }


def _transform_to_texture_index(
    data: dict[str, Any],
    key: str,
    texture_name_2_index: dict[str, int],
    not_found_textures: set[str],
) -> None:
    # {  ###
    texture_name = data[key].removeprefix("_")
    assert isinstance(texture_name, str)

    if texture_name.lower() == "undefined":
        data[key] = -1
        return

    if texture_name in texture_name_2_index:
        data[key] = texture_name_2_index[texture_name]
    else:
        not_found_textures.add(texture_name)
    # }


def _transform_to_texture_indices_list(
    data: dict[str, Any],
    key: str,
    texture_name_2_index: dict[str, int],
    not_found_textures: set[str],
) -> None:
    # {  ###
    textures = data[key]
    assert isinstance(textures, list)

    for i, texture_name_ in enumerate(textures):
        texture_name = texture_name_.removeprefix("_")
        if texture_name.lower() == "undefined":
            textures[i] = -1
        else:
            if texture_name in texture_name_2_index:
                textures[i] = texture_name_2_index[texture_name]
            else:
                not_found_textures.add(texture_name)
    # }


@timing
def convert_gamelib_json_to_binary(
    platform: bf.BuildPlatform,
    texture_name_2_id: dict[str, int],
    genline,
    atlas_data,
    original_texture_sizes,
) -> None:
    gamelib = bf.load_gamelib_cached()

    gamelib["original_texture_sizes"] = original_texture_sizes

    # Colors.
    # {  ###
    if 1:
        used_color_names = set()
        genline("// Usage: PAL_ORANGE, PAL_TEXT_ORANGE.")
        genline("#define PAL_COLORS_TABLE \\")
        for i, hex_color_ in enumerate(bf.game_settings.colors):
            hex_color = hex_color_[1:].lower()

            color_name = bf.game_settings.computed_color_names[i]
            assert color_name not in used_color_names, color_name
            used_color_names.add(color_name)

            color_type = color_name.upper().replace(" ", "_")

            gamelib["colors"].append({"type": color_type, "color": f"0x{hex_color}ff"})

            genline(
                '  X("{}", 0x{}ff, {}){}'.format(
                    hex_color_.lower(),
                    hex_color,
                    color_type,
                    "   \\" if i < len(bf.game_settings.colors) - 1 else "\n",
                )
            )

    # }

    # Imgui debug variables.
    # {  ###
    if 1:
        debug_variables = gamelib.pop("debug_variables", [])
        genline("struct BFDebug {")
        for var in debug_variables:
            t, n = var["type"], var["name"]
            genline(f"  {t} {n} = {{}};")
        genline("} gdebug = {};\n")

        genline(
            "void BF_IM_ReadLine(ImGuiContext*, ImGuiSettingsHandler*, void*, const char* line) {"
        )
        for var in debug_variables:
            t, n = var["type"], var["name"]
            matched_type = {"int": "int", "bool": "int", "f32": "f32"}[t]
            genline(f"  {matched_type} toRead_{n} = {{}};")

        addedVar = False
        for var in debug_variables:
            t, n = var["type"], var["name"]
            prefix = "else " if addedVar else ""
            match t:
                case "bool":
                    genline(
                        f'  {prefix}if (sscanf(line, "{n}=%d", &toRead_{n}) == 1) {{ gdebug.{n} = (bool)toRead_{n}; }}'
                    )
                case "int":
                    genline(
                        f'  {prefix}if (sscanf(line, "{n}=%d", &toRead_{n}) == 1) {{ gdebug.{n} = toRead_{n}; }}'
                    )
                case "f32":
                    genline(
                        f'  {prefix}if (sscanf(line, "{n}=%f", &toRead_{n}) == 1) {{ gdebug.{n} = toRead_{n}; }}'
                    )
                case _:
                    raise NotImplementedError
            addedVar = True
        genline("}\n")

        genline(
            "void BF_IM_WriteAll(ImGuiContext*, ImGuiSettingsHandler*, ImGuiTextBuffer* buf) {"
        )
        genline('  buf->appendf("[UserData][Main]\\n");')
        for var in debug_variables:
            t, n = var["type"], var["name"]
            match t:
                case "bool":
                    genline(f'  buf->appendf("{n}=%d\\n", (int)gdebug.{n});')
                case "int":
                    genline(f'  buf->appendf("{n}=%d\\n", gdebug.{n});')
                case "f32":
                    genline(f'  buf->appendf("{n}=%f\\n", gdebug.{n});')
                case _:
                    raise NotImplementedError
        genline("}\n")
    # }

    # Sounds.
    # {  ###
    postload_files = []

    def next_postload_file_index(path: Path) -> int:
        postload_files.append(path.as_posix())
        return len(postload_files)

    do_audio(platform)

    sound_paths = [*bf.RES_DIR.glob("*.ogg")]
    if platform.is_web():
        sound_paths.extend((bf.PROJECT_DIR / "resp").glob("*.ogg"))

    m = 2**32
    sound_types_ = [
        (t, (bf.stable_hash(t) % m))
        for t in {sound_path.stem.split("__", 1)[0].upper() for sound_path in sound_paths}
    ]
    sound_types_for_humans = sorted(x[0] for x in sound_types_)
    sound_types_.sort(key=lambda x: x[1])
    sound_types_sorted_by_enum_value: list[str] = [x[0] for x in sound_types_]
    sound_enum_values = [x[1] for x in sound_types_]
    bf.genenum(
        genline,
        "Sound",
        sound_types_for_humans,
        override_values=[
            sound_types_sorted_by_enum_value.index(x) for x in sound_types_for_humans
        ],
    )

    genline("constexpr u32 SOUND_TO_HASH_VALUE_[]{  ///")
    for t in sound_enum_values:
        genline(f"  {t},")
    genline("};")
    genline("VIEW_FROM_ARRAY_DANGER(SOUND_TO_HASH_VALUE);\n")

    sound_variations_per_type: dict[str, list[Any]] = defaultdict(list)

    for sound_path in sound_paths:
        filepath = sound_path.relative_to(bf.PROJECT_DIR)

        postload_index = 0
        if (sound_path.parent.name == "resp") and platform.is_web():
            postload_index = next_postload_file_index(filepath)

        sound_variations_per_type[sound_path.stem.split("__", 1)[0].upper()].append(
            {
                "filepath": filepath.as_posix(),
                "postload_index": postload_index,
            }
        )

    existing_sounds_by_type = {x.pop("type"): x for x in gamelib.get("sounds", [])}

    sounds: list[Any] = []
    gamelib["sounds"] = sounds
    sound_index = -1
    for sound_type, enum_value_id in sound_types_:
        assert enum_value_id > 0
        sound_index += 1
        is_music = sound_type.startswith("MUSIC_")
        kwargs = {}
        if is_music:
            kwargs["pitch_min"] = 1
            kwargs["pitch_max"] = 1
        x = {
            "index": sound_index,
            "enum_value_id": enum_value_id,
            "variations": sound_variations_per_type[sound_type],
            "is_music": is_music,
            **kwargs,
            **existing_sounds_by_type.pop(sound_type, {}),
        }
        sounds.append(x)

    if existing_sounds_by_type:
        bf.log.warning(
            "gamelib.yml `sounds` contain those that aren't bound to any exported sounds: {}".format(
                ", ".join(existing_sounds_by_type)
            )
        )
    # }

    gamelib |= atlas_data
    bf.genenum(genline, "DrawZ", gamelib.pop("draw_z"), add_count=True)

    localization_codepoints, locale_to_index = _do_localization(genline, gamelib)

    warnings = 0

    def warning(*args, **kwargs) -> None:
        nonlocal warnings
        warnings += 1
        bf.log.warning(*args, **kwargs)

    for gamelib_processing_function in bf.gamelib_processing_functions:
        gamelib_processing_function(genline, gamelib, localization_codepoints, warning)

    genline(f"constexpr bool BUILD_WARNINGS = {warnings};\n")

    # Checking textures.
    # ============================================================
    # {  ###
    if 1:
        not_found_textures: set[str] = set()
        transform_texture_id = lambda data, key: _transform_to_texture_index(
            data,
            key,
            texture_name_2_index=texture_name_2_id,
            not_found_textures=not_found_textures,
        )
        transform_texture_ids_list = lambda data, key: _transform_to_texture_indices_list(
            data,
            key,
            texture_name_2_index=texture_name_2_id,
            not_found_textures=not_found_textures,
        )
        texture_ids_recursive_transform(
            gamelib, transform_texture_id, transform_texture_ids_list
        )
        if not_found_textures:
            assert False, "Couldn't find textures:\n{}".format(
                "\n".join(sorted(f"- {x}" for x in not_found_textures))
            )
    # }

    degrees_to_radians_recursive_transform(gamelib)

    bf.recursive_replace_transform(gamelib, "locale", "locales", locale_to_index)
    bf.recursive_replace_transform(
        gamelib, "sound_hash", "sound_hashes", dict(sound_types_)
    )

    genline(
        f"constexpr int BF_TOTAL_POSTLOAD_FILES_PLUS_ONE = {len(postload_files) + 1};\n"
    )
    gamelib["postload_files"] = postload_files

    # Creation of `gamelib.bin`.
    # {  ###
    intermediate_path = bf.TEMP_DIR / "gamelib.intermediate.jsonc"
    intermediate_path.write_text(json.dumps(gamelib, indent=4), newline="\n")
    bf.run_command(
        [
            bf.FLATC_PATH,
            "-o",
            bf.TEMP_DIR,
            "-b",
            bf.GAME_DIR / "bf_gamelib.fbs",
            intermediate_path,
        ]
    )

    intermediate_binary_path = Path(str(intermediate_path).rsplit(".", 1)[0] + ".bin")
    shutil.move(intermediate_binary_path, bf.RES_DIR / "gamelib.bin")
    # }


def downscale_images(downscale_factors: list[int]) -> None:
    # {  ###
    assert downscale_factors, downscale_factors

    images_to_downscale = list(bf.ART_TEXTURES_DIR.glob("*.png"))

    for factor in downscale_factors:
        assert factor >= 1, factor

        bf.log.info("Downscaling by {}".format(factor))

        export_dir = bf.TEMP_ART_DIR / f"d{factor}"
        bf.recursive_mkdir(export_dir)

        for image_path in images_to_downscale:
            s1 = image_path.stat()

            export_image_path = export_dir / image_path.name

            if export_image_path.exists() and (
                s1.st_mtime_ns == export_image_path.stat().st_mtime_ns
            ):
                continue

            im = Image.open(image_path)
            im.thumbnail(
                (im.size[0] // factor, im.size[1] // factor), Image.Resampling.LANCZOS
            )
            im.save(export_image_path, "PNG")
            os.utime(export_image_path, ns=(s1.st_atime_ns, s1.st_mtime_ns))
    # }


def texture_cmp_key(x: dict, factor: int) -> tuple[bool, str]:
    return (x["debug_name"] != f"d{factor}/undefined", x["debug_name"])


@timing
def make_atlases(downscale_factors: list[int]) -> tuple[dict[str, int], list[dict]]:
    # {  ###
    assert downscale_factors, downscale_factors

    texture_name_2_id: dict[str, int] = {}
    atlases_data = []

    for factor in downscale_factors:
        path = bf.ART_DIR / f"atlas_d{factor}.ftpp"

        cache_filepath = bf.TEMP_DIR / f".atlas_d{factor}.cache"

        old_cache_value = -1
        if cache_filepath.exists():
            old_cache_value = int(cache_filepath.read_text())

        cache_value = 0
        for filepath in Path(bf.TEMP_ART_DIR / f"d{factor}").rglob("*.png"):
            cache_value = bf.stable_hash(
                cache_value
                + bf.stable_hash(filepath.stat().st_mtime_ns)
                + bf.stable_hash(filepath.name)
            )

        should_regenerate_atlas = False
        temp_atlas_path = bf.TEMP_DIR / (path.stem + ".png")

        if (cache_value == old_cache_value) and temp_atlas_path.exists():
            bf.log.info("Skipped atlas generation - no images changed")
            timing_mark("skipped png generation")
        else:
            # Генерируем атлас из .ftpp файла. Создаются .json спецификация и .png текстура.
            bf.log.info("Generating atlas...")
            bf.run_command("free-tex-packer-cli --project {}".format(path))

            cache_filepath.write_text(str(cache_value), newline="\n")

            should_regenerate_atlas = True

        # Подгоняем спецификацию под наш формат.
        json_path = bf.TEMP_DIR / (path.stem + ".json")
        with open(json_path) as json_file:
            json_data = json.load(json_file)

        found_textures: set[str] = set()

        textures: list[Any] = []
        for name_, data in json_data["frames"].items():
            name = name_.removeprefix("art/")

            assert name not in found_textures
            found_textures.add(name)

            texture_data = {
                "id": -1,
                "debug_name": name,
                "size_x": data["frame"]["w"],
                "size_y": data["frame"]["h"],
                "atlas_x": data["frame"]["x"],
                "atlas_y": data["frame"]["y"],
                "baseline": 0,
            }
            textures.append(texture_data)

        textures.sort(key=partial(texture_cmp_key, factor=factor))

        if not texture_name_2_id:
            assert textures, textures

            for i, texture in enumerate(textures):
                texture["id"] = i
                name = texture["debug_name"].removeprefix(f"d{factor}/").removeprefix("_")
                texture_name_2_id[name] = i

        bf.recursive_mkdir(bf.RES_DIR)

        out_atlas_path = bf.RES_DIR / (path.stem + ".basis")
        if not out_atlas_path.exists() or should_regenerate_atlas:
            bf.run_command(
                [
                    bf.PROJECT_DIR / "cli" / "basisu.exe",
                    "-uastc",
                    "-slower",
                    "-file",
                    temp_atlas_path,
                    "-output_file",
                    out_atlas_path,
                ],
                cwd=bf.TEMP_DIR,
            )

            bf.run_command(
                [
                    bf.PROJECT_DIR / "cli" / "basisu.exe",
                    "-validate",
                    "-file",
                    out_atlas_path,
                ],
                cwd=bf.TEMP_DIR,
            )

        else:
            timing_mark(f"{factor}: skipped optimized copying")

        atlases_data.append(
            {
                "atlas_downscale_factor": factor,
                "atlas_textures": textures,
                "atlas_size_x": json_data["meta"]["size"]["w"],
                "atlas_size_y": json_data["meta"]["size"]["h"],
            }
        )

    return texture_name_2_id, atlases_data
    # }


def remove_excessive_files_by_pattern(
    src_dir: str | Path, dst_dir: str | Path, pattern: str
) -> None:
    # {  ###
    dst_filepaths = [
        filepath.relative_to(dst_dir) for filepath in Path(dst_dir).glob(pattern)
    ]
    src_filepaths = [
        filepath.relative_to(src_dir) for filepath in Path(src_dir).glob(pattern)
    ]

    excessive_files = []

    for dst_filepath in dst_filepaths:
        if dst_filepath not in src_filepaths:
            p = Path(dst_dir) / dst_filepath
            p.unlink()
            excessive_files.append(str(p))

    if excessive_files:
        bf.log.info("Removed excessive files: {}".format(", ".join(excessive_files)))
    # }


@timing
def remove_excessive_images_in_temp_art_dir(downscale_factors: list[int]) -> None:
    # {  ###
    for factor in downscale_factors:
        TEMP_ART_DOWNSCALED_DIR = bf.TEMP_ART_DIR / f"d{factor}"
        remove_excessive_files_by_pattern(
            bf.ART_TEXTURES_DIR, TEMP_ART_DOWNSCALED_DIR, "*.png"
        )
    # }


@timing
def remove_intermediate_generation_files() -> None:
    for filepath in bf.TEMP_DIR.rglob("*.intermediate*"):
        filepath.unlink()


def listfiles_with_hashes_in_dir(path: str | Path) -> dict[str, int]:
    # {  ###
    filepath_string_to_hash = {}

    for filepath in Path(path).rglob("*"):
        with open(filepath, "rb") as in_file:
            filepath_string_to_hash[str(filepath.relative_to(path))] = hash(
                in_file.read()
            )

    return filepath_string_to_hash
    # }


@timing
def generate_flatbuffer_files():
    # {  ###
    bf.recursive_mkdir(bf.FLATBUFFERS_GENERATED_DIR)

    hashes_for_msbuild = listfiles_with_hashes_in_dir(bf.FLATBUFFERS_GENERATED_DIR)

    # Генерируем cpp файлы из FlatBuffer (.fbs) файлов.
    flatbuffer_files = list(bf.SRC_DIR.rglob("*.fbs"))

    with tempfile.TemporaryDirectory() as td:

        def gen(filepaths, *args):
            command = [
                bf.FLATC_PATH,
                *args,
                "-o",
                td,
                "--cpp",
                *list(filepaths),
            ]

            bf.run_command(command)

        gen(
            (
                i
                for i in flatbuffer_files
                if i.name in bf.game_settings.generate_flatbuffers_api_for
            ),
            "--gen-object-api",
            "--reflect-names",
        )
        gen(
            i
            for i in flatbuffer_files
            if i.name not in bf.game_settings.generate_flatbuffers_api_for
        )

        for file, file_hash in listfiles_with_hashes_in_dir(td).items():
            # Костыль, чтобы MSBuild не ребилдился каждый раз.
            if file_hash != hashes_for_msbuild.get(file):
                shutil.copyfile(Path(td) / file, bf.FLATBUFFERS_GENERATED_DIR / file)
    # }


@timing
def remove_orphan_resources_files(
    platform: bf.BuildPlatform, build_type: bf.BuildType
) -> None:
    # {  ###
    match platform:
        case bf.BuildPlatform.Win:
            target_dir_ = f".cmake/vs17/{build_type}/res"

        case _:
            if platform.is_web():
                target_dir_ = f".cmake/{platform}_{build_type}/res"
            else:
                assert False, f"Not supported platform: {platform}"

    src_files = {f.name for f in bf.RES_DIR.iterdir() if f.is_file()}

    target_dir = Path(target_dir_)

    if not target_dir.exists():
        return

    for file in target_dir.iterdir():
        if file.is_file() and file.name not in src_files:
            file.unlink()
            bf.log.info(f"Removed orphan res/ file '{file}'")
    # }


@timing
def get_sounds_that_reaper_would_export() -> set[str]:
    sounds: set[str] = set()

    project = rpp.loads((bf.ASSETS_DIR / "sfx" / "src" / "sfx.rpp").read_text())
    for t in project.findall(".//TRACK"):
        for f in t.findall(".//FILE"):
            subproject_path = Path(f[1])
            subproject = rpp.loads(
                (
                    bf.ASSETS_DIR / "sfx" / "src" / "_sfx" / subproject_path.name
                ).read_text()
            )

            for marker in subproject.findall(".//MARKER"):
                marker_name = marker[3]
                marker_number = marker[1]
                if marker_name not in ("=START", "=END"):
                    sounds.add(
                        "{}__{:02}".format(subproject_path.stem, int(marker_number))
                    )

    return sounds


@timing
def cfy_fonts() -> None:
    allowed_chars = string.ascii_lowercase + string.digits + "_"
    for filepath in (bf.SRC_DIR / "engine" / "fonts").glob("*"):
        out_name = (
            bf.replace_double_spaces(
                "".join(c if c in allowed_chars else " " for c in filepath.name.lower())
            )
            .replace(" ", "_")
            .strip("_")
        )
        bf.run_command(
            [
                r".\cli\binary_to_compressed_c.exe",
                filepath,
                "codegen_" + out_name,
                ">",
                CODEGEN_DIR / "fonts" / (out_name + ".c"),
            ]
        )


@timing
def regenerate_shaders(building_for_release: bool) -> None:
    # {  ###
    output_directory = CODEGEN_DIR / "shaders"
    if output_directory.exists():
        bf.run_command(["del", "/f/s/q", output_directory])
        output_directory.mkdir(exist_ok=True)
    bf.recursive_mkdir(output_directory)

    with open(
        output_directory / "include_all.h", "w", encoding="utf-8", newline="\n"
    ) as include_all_file:
        include_all_file.write("#pragma once\n\n")

        found_shader_names = set()
        all_shaders_by_type = {  # type: ignore[var-annotated]
            "fragment": [],
            "vertex": [],
        }
        shader_suffix_to_shader_type = {
            "_fs.sc": "fragment",
            "_vs.sc": "vertex",
            ".gitkeep": "skip",
            ".def.sc": "skip",
            ".sh": "skip",
        }
        incorrect_shaders = []

        for base in (
            bf.SRC_DIR / "engine" / "shaders",
            bf.SRC_DIR / "game" / "shaders",
        ):
            for shader in base.glob("*"):
                shader_type = None
                for suffix, shader_type_ in shader_suffix_to_shader_type.items():
                    if shader.name.endswith(suffix):
                        shader_type = shader_type_
                        break

                if shader_type is None:
                    incorrect_shaders.append(str(shader))

                elif shader_type != "skip":
                    assert shader.stem not in found_shader_names, (
                        f"Shader '{shader.stem}' is an engine's shader. Rename it!"
                    )
                    found_shader_names.add(shader.stem)
                    all_shaders_by_type[shader_type].append(shader)

        assert not incorrect_shaders, (
            "Found files in shaders directories with unknown type.\n"
            "Their names should end with suffixes: {}.\n{}"
        ).format(", ".join(shader_suffix_to_shader_type), "\n".join(incorrect_shaders))

        for shader_type, shaders in all_shaders_by_type.items():
            for shader in shaders:
                varyingdef = str(shader).rsplit("_", 1)[0] + "_var.def.sc"

                for additional_args, name_suffix in (
                    ("--platform linux   -p 120", "glsl"),
                    ("--platform android -p 100_es", "essl"),
                    ("--platform linux   -p spirv", "spv"),
                    (
                        "--platform windows -p s_4_0"
                        + (" -O 3 " if building_for_release else ""),
                        "dx11",
                    ),
                    (
                        (
                            "--platform ios -p metal"
                            + (" -O 3 " if building_for_release else "")
                        ),
                        "mtl",
                    ),
                ):
                    out_file = Path(
                        f"{output_directory / shader.stem}_{name_suffix}.bin.h"
                    )
                    include_all_file.write(f'#include "shaders/{out_file.name}"\n')

                    bf.run_command(
                        bf.replace_double_spaces(
                            f"""
                            {bf.SHADERC_PATH}
                            --type {shader_type}
                            -f {shader}
                            -o {out_file}
                            {additional_args}
                            -i {bf.PROJECT_DIR / "vendor" / "bgfx" / "src"}
                            --varyingdef {varyingdef}
                            --Werror
                            --bin2c
                            """.replace("\n", " ")
                        )
                    )
    # }


@timing
def do_generate(platform: bf.BuildPlatform, build_type: bf.BuildType) -> None:
    # {  ###
    remove_orphan_resources_files(platform, build_type)

    # Removing old codegen files.
    for folder in ("flatbuffers", "fonts", "hands"):
        target_folder = CODEGEN_DIR / folder
        if target_folder.exists():
            bf.run_command(["del", "/f/s/q", target_folder])
            target_folder.mkdir(exist_ok=True)

    cfy_fonts()

    # Generating shell.
    if build_type == bf.BuildType.Release and platform.is_web():
        shell_file = bf.VENDOR_DIR / "shell_release.html"
        shell_contents = shell_file.read_text(encoding="utf-8")

        NOT_YANDEX_WEB_POST_RUN = """
            () => {
                const isMobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent);
                var device = 0;
                if (isMobile)
                    device = 1;
                Module.fromJS_setDeviceType(device);
            },
        """

        variables = {
            bf.BuildPlatform.Web: {
                "EXTEND_BODY_START": "",
                "EXTEND_BEFORE_WASM": """
                    performance.mark("jsBeforeWASM");
                """,
                "EXTEND_PRE_RUN": """
                    function() {
                        performance.mark("jsPreRun");
                    },
                    function() {
                        performance.mark("jsWebsocketConnecting");

                        const dep = "websocket";
                        Module.addRunDependency(dep);

                        const wsUrl = "ws://THIS_PC_LOCAL_IP:8003";
                        const LOG_WS = new WebSocket(wsUrl);

                        const finish = () => {
                            performance.mark("jsWebsocketConnectionFinished");
                            performance.measure(
                                "Websocket Connection",
                                "jsWebsocketConnecting",
                                "jsWebsocketConnectionFinished"
                            );
                            Module.removeRunDependency(dep);
                        };
                        LOG_WS.onopen = finish;
                        LOG_WS.onerror = (err) => { finish(); };
                        LOG_WS.onclose = (err) => { finish(); };

                        const oldLog = console.log;
                        console.log = (...args) => {
                            if (LOG_WS.readyState === WebSocket.OPEN)
                                LOG_WS.send("log: " + args.join(" "));
                            oldLog(...args);
                        };
                        const oldWarn = console.warn;
                        console.warn = (...args) => {
                            if (LOG_WS.readyState === WebSocket.OPEN)
                                LOG_WS.send("warn: " + args.join(" "));
                            oldWarn(...args);
                        };
                        const oldError = console.error;
                        console.error = (...args) => {
                            if (LOG_WS.readyState === WebSocket.OPEN)
                                LOG_WS.send("error: " + args.join(" "));
                            oldError(...args);
                        };
                        window.addEventListener("error", (e) => {
                          console.error(e.message);
                        });
                        window.addEventListener("unhandledrejection", (e) => {
                          console.error("unhandledrejection:", e.reason);
                        });

                    },
                """.replace("THIS_PC_LOCAL_IP", bf.get_local_ip()),
                "EXTEND_POST_RUN": NOT_YANDEX_WEB_POST_RUN,
                "EXTEND_MAIN_SCRIPT": """
                    const moduleReady = new Promise(resolve => {
                        Module.onRuntimeInitialized = resolve;
                    });

                    (async () => {
                        await moduleReady;
                        performance.mark("jsRuntimeInitialized");
                        performance.measure(
                            "WASM Startup", "jsBeforeWASM", "jsRuntimeInitialized"
                        );
                    })();
                """,
                "EXTEND_HTML_END": "",
            },
            bf.BuildPlatform.WebItch: {
                "EXTEND_BODY_START": "",
                "EXTEND_BEFORE_WASM": "",
                "EXTEND_PRE_RUN": "",
                "EXTEND_POST_RUN": NOT_YANDEX_WEB_POST_RUN,
                "EXTEND_MAIN_SCRIPT": "",
                "EXTEND_HTML_END": "",
            },
            bf.BuildPlatform.WebYandex: {
                "EXTEND_BODY_START": """
                    <script src="/sdk.js"></script>
                    <!-- Yandex.Metrika counter -->
                    <script type="text/javascript">
                        window.yandexMetricaCounterId = YANDEX_METRIC_COUNTER_ID;
                        (function(m,e,t,r,i,k,a){
                            m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
                            m[i].l=1*new Date();
                            for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
                            k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)
                        })(window, document,'script','https://mc.yandex.ru/metrika/tag.js?id=YANDEX_METRIC_COUNTER_ID', 'ym');

                        ym(YANDEX_METRIC_COUNTER_ID, 'init', {ssr:true, clickmap:true, accurateTrackBounce:true, trackLinks:true});
                    </script>
                    <noscript><div><img src="https://mc.yandex.ru/watch/YANDEX_METRIC_COUNTER_ID" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
                    <!-- /Yandex.Metrika counter -->
                """.replace(
                    "YANDEX_METRIC_COUNTER_ID",
                    str(bf.game_settings.yandex_metrica_counter_id),
                ),
                "EXTEND_BEFORE_WASM": "",
                "EXTEND_PRE_RUN": "",
                "EXTEND_POST_RUN": "",
                "EXTEND_MAIN_SCRIPT": """
                    const moduleReady = new Promise(resolve => {
                        Module.onRuntimeInitialized = resolve;
                    });

                    (async () => {
                        window.ysdk = await YaGames.init();
                        await moduleReady;
                        if (window.ysdk.deviceInfo.isMobile()
                            || window.ysdk.deviceInfo.isTablet())
                            Module.fromJS_setDeviceType(1);
                        window.player = await window.ysdk.getPlayer();
                        Module.fromJS_markYsdkLoaded();

                        window.ysdk.on('game_api_pause', () => {
                            Module.fromJS_setYsdkPaused(1);
                        });
                        window.ysdk.on('game_api_resume', () => {
                            Module.fromJS_setYsdkPaused(0);
                        });

                        var lang = 1;
                        const languages_map = {
                            ru: 0,
                            be: 0,
                            kk: 0,
                            uk: 0,
                            uz: 0,
                            en: 1,
                        };
                        const l = window.ysdk.environment.i18n.lang;
                        if (l in languages_map)
                            lang = languages_map[l];
                        Module.fromJS_setLocalization(lang);
                    })();
                """,
                "EXTEND_HTML_END": "",
            },
        }[platform]

        for variable, value in variables.items():
            var = f"##{variable}##"
            assert var in shell_contents
            shell_contents = shell_contents.replace(var, value)

        assert "##" not in shell_contents

        name = "shell_release"
        if suffix := platform.lower().removeprefix("web"):
            name += "_" + suffix
        (bf.TEMP_DIR / f"{name}.html").write_text(
            shell_contents, encoding="utf-8", newline="\n"
        )

    # Shaders.
    # regenerate_shaders(build_type != BuildType.Debug)

    bf.recursive_mkdir(bf.HANDS_GENERATED_DIR)

    if platform.is_web():
        bind_function_names: set[str] = set()
        for f in (bf.SRC_DIR / "engine" / "bf_engine.cpp",):
            m = re.findall(r"\s+(fromJS_\w+)", f.read_text(encoding="utf-8"))
            if m:
                bind_function_names |= set(m)

        (bf.HANDS_GENERATED_DIR / "bf_emscripten_binds.cpp").write_text(
            """{}EMSCRIPTEN_BINDINGS(callbacks) {{
{}}}""".format(
                CODEGEN_DISCLAIMER,
                "".join(
                    f'  emscripten::function("{x}", &{x});\n'
                    for x in sorted(bind_function_names)
                ),
            ),
            encoding="utf-8",
            newline="\n",
        )

    with open(
        bf.HANDS_GENERATED_DIR / "bf_codegen.cpp", "w", encoding="utf-8", newline="\n"
    ) as codegen_file:
        codegen_file.write(CODEGEN_DISCLAIMER)

        def genline(value):
            codegen_file.write(value)
            codegen_file.write("\n")

        generate_flatbuffer_files()

        remove_intermediate_generation_files()

        # TODO: downscale_factors = [1, 2, 4]
        downscale_factors = [2, 1]

        remove_excessive_images_in_temp_art_dir(downscale_factors)
        downscale_images(downscale_factors)
        downscale_factors.pop()

        textures = [
            {
                "debug_name": f"d1/{filepath.stem}",
                "size": Image.open(bf.TEMP_ART_DIR / "d1" / filepath).size,
            }
            for filepath in Path(bf.TEMP_ART_DIR / "d1").glob("*.png")
        ]
        textures.sort(key=partial(texture_cmp_key, factor=1))
        original_texture_sizes = [x["size"] for x in textures]

        texture_name_2_id, atlases_data = make_atlases(downscale_factors)
        assert len(downscale_factors) == 1
        convert_gamelib_json_to_binary(
            platform, texture_name_2_id, genline, atlases_data[0], original_texture_sizes
        )

        genline("///")

    symlink_resources_for = (
        (bf.BuildPlatform.Win, bf.BuildType.Debug),
        (bf.BuildPlatform.Win, bf.BuildType.RelWithDebInfo),
        (bf.BuildPlatform.Win, bf.BuildType.Release),
        (bf.BuildPlatform.Web, bf.BuildType.Debug),
        (bf.BuildPlatform.Web, bf.BuildType.Release),
        (bf.BuildPlatform.WebItch, bf.BuildType.Release),
        (bf.BuildPlatform.WebYandex, bf.BuildType.Release),
    )
    dist_dir = {
        (bf.BuildPlatform.Win, bf.BuildType.Debug): ".cmake/vs17/Debug/",
        (
            bf.BuildPlatform.Win,
            bf.BuildType.RelWithDebInfo,
        ): ".cmake/vs17/RelWithDebugInfo/",
        (bf.BuildPlatform.Win, bf.BuildType.Release): ".cmake/vs17/Release/",
        (bf.BuildPlatform.Web, bf.BuildType.Debug): ".cmake/Web_Debug/",
        (bf.BuildPlatform.Web, bf.BuildType.Release): ".cmake/Web_Release/",
        (bf.BuildPlatform.WebItch, bf.BuildType.Release): ".cmake/WebItch_Release/",
        (bf.BuildPlatform.WebYandex, bf.BuildType.Release): ".cmake/WebYandex_Release/",
    }[(platform, build_type)]

    bf.recursive_mkdir(dist_dir)

    resources_folders = ["res"]
    if platform.is_web():
        resources_folders.append("resp")

    if (platform, build_type) in symlink_resources_for:
        for folder in resources_folders:
            p = Path(dist_dir + folder)
            if not p.exists():
                p.symlink_to(bf.PROJECT_DIR / folder, target_is_directory=True)
    else:
        dst_resources = dist_dir + "res/"
        remove_excessive_files_by_pattern(bf.RES_DIR, dst_resources, "*")
        shutil.copytree(bf.RES_DIR, dst_resources, dirs_exist_ok=True)
    # }


###
