# Imports.  {  ###
import json
from pathlib import Path

import bf_lib as bf
import rpp
import yaml
from bf_game import *  # noqa
from bf_typer import timing

# }


@timing
def get_sounds_that_reaper_would_export() -> set[str]:
    # {  ###
    sounds: set[str] = set()

    project = rpp.loads((bf.ASSETS_DIR / "sfx" / "src" / "sfx.rpp").read_text())
    for t in project.findall(".//TRACK"):
        for f in t.findall(".//FILE"):
            subproject_path = Path(f[1])
            subproject = rpp.loads(
                (
                    bf.ASSETS_DIR / "sfx" / "src" / "_sfx" / subproject_path.name
                ).read_text()
            )

            for marker in subproject.findall(".//MARKER"):
                marker_name = marker[3]
                marker_number = marker[1]
                if marker_name not in ("=START", "=END"):
                    sounds.add(
                        "{}__{:02}".format(subproject_path.stem, int(marker_number))
                    )

    return sounds
    # }


@timing
def do_audio(_platform: bf.BuildPlatform) -> None:
    # {  ###
    AUDIO_SRC_DIR = bf.ASSETS_DIR / "sfx"
    src_files = {p for p in AUDIO_SRC_DIR.glob("*.ogg") if p.is_file()}

    # Removing sound files that wouldn't be exported by reaper.
    allowed_sounds = get_sounds_that_reaper_would_export()
    for src_file in src_files:
        if src_file.stem.startswith("music_"):
            continue
        if src_file.stem not in allowed_sounds:
            src_file.unlink()
    # }


# def downscale_images(downscale_factors: list[int]) -> None:
#     # {  ###
#     assert downscale_factors, downscale_factors
#
#     images_to_downscale = list(bf.ART_TEXTURES_DIR.glob("*.png"))
#
#     for factor in downscale_factors:
#         assert factor >= 1, factor
#
#         bf.log.info("Downscaling by {}".format(factor))
#
#         export_dir = bf.TEMP_ART_DIR / f"d{factor}"
#         bf.recursive_mkdir(export_dir)
#
#         for image_path in images_to_downscale:
#             s1 = image_path.stat()
#
#             export_image_path = export_dir / image_path.name
#
#             if export_image_path.exists() and (
#                 s1.st_mtime_ns == export_image_path.stat().st_mtime_ns
#             ):
#                 continue
#
#             im = Image.open(image_path)
#             im.thumbnail(
#                 (im.size[0] // factor, im.size[1] // factor), Image.Resampling.LANCZOS
#             )
#             im.save(export_image_path, "PNG")
#             os.utime(export_image_path, ns=(s1.st_atime_ns, s1.st_mtime_ns))
#     # }


@timing
def do_generate(platform: bf.BuildPlatform, _build_type: bf.BuildType) -> None:
    bf.run_command(
        """
        godot
        --headless
        -s addons/protobuf/protobuf_cmdln.gd
        --input=src/game/glib.proto
        --output=.temp/glib.gd
        """,
    )
    with Path("src/codegen/nolint/glib.gd").open("w", encoding="utf-8") as out_file:
        out_file.write("""extends Node
static var v: Lib = Lib.new()

func ToVector2(value: GPos2) -> Vector2:
    return Vector2(value.get_x(), value.get_y())

func ToVector2i(value: GPos2i) -> Vector2i:
    return Vector2i(value.get_x(), value.get_y())

func ToVector3(value: GPos3) -> Vector3:
    return Vector3(value.get_x(), value.get_y(), value.get_z())

func ToVector3i(value: GPos3i) -> Vector3i:
    return Vector3i(value.get_x(), value.get_y(), value.get_z())

func _ready() -> void:
	var glib_file = FileAccess.open("res://assets/glib.binpb", FileAccess.READ)
	assert(glib_file)
	var glib_bytes: PackedByteArray = glib_file.get_buffer(glib_file.get_length())
	glib_file.close()
	var err = v.from_bytes(glib_bytes)
	assert(not err)

""")

        out_file.write(Path(".temp/glib.gd").read_text(encoding="utf-8"))
    bf.run_command("gdscript-formatter src/codegen/nolint/glib.gd")
    with open("src/game/glib.yaml", encoding="utf-8") as glib_file:
        glib = yaml.safe_load(glib_file)
    with open(
        "src/codegen/hands.gd", "w", encoding="utf-8", newline="\n"
    ) as codegen_file:

        def genline(value):
            codegen_file.write(value)
            codegen_file.write("\n")

        genline("# automatically generated by bf_cli.py, do not modify")
        genline("class_name Codegen")

        do_audio(platform)
    out_path = Path(".temp") / "glib.json"
    bf.recursive_mkdir(out_path.parent)
    with open(out_path, "w", encoding="utf-8") as out_file:
        json.dump(glib, out_file, indent=2)
    bf.run_command(
        rf"buf convert src/game/glib.proto --type=Lib --from={out_path} --to=assets/glib.binpb"
    )


###
