# automatically generated by bf_cli.py, do not modify
class_name Codegen
enum GProgressionType {
	///GProgressionType_INVALID,
	GProgressionType_SKILL_HP,
	GProgressionType_SKILL_MANA,
	GProgressionType_SKILL_ATTACK,
	GProgressionType_SKILL_ARMOR,
	GProgressionType_SKILL_MAGIC_ATTACK,
	GProgressionType_CRAFT_BLACKSMITH,
	GProgressionType_CRAFT_WITCH,
	GProgressionType_CRAFT_ENGINEER,
	GProgressionType_CLASS_HEAVY_KNIGHT,
	GProgressionType_CLASS_BARBARIAN,
	GProgressionType_COUNT,
}
