# automatically generated by bf_cli.py, do not modify
class_name Codegen
enum GProgressionType {
	INVALID,
	SKILL_HP,
	SKILL_MANA,
	SKILL_ATTACK,
	SKILL_ARMOR,
	SKILL_MAGIC_ATTACK,
	CRAFT_BLACKSMITH,
	CRAFT_WITCH,
	CRAFT_ENGINEER,
	CLASS_HEAVY_KNIGHT,
	CLASS_BARBARIAN,
	COUNT,
}
